version: '3'
services:
    web:
        build:
            context: .
            dockerfile: docker/web/Dockerfile
        env_file: .env
        environment:
            - MONGO_USERNAME=$MONGO_USERNAME
            - MONGO_PASSWORD=$MONGO_PASSWORD
            - MONGO_HOSTNAME=db
            - MONGO_PORT=$MONGO_PORT
            - MONGO_DB=$MONGO_DB
        ports:
            - "80:8080"
        volumes:
            - .:/home/deno/app
        tty: true
        restart: always
        networks:
            - app-network
        command: sh -c "/home/deno/app/wait-for.sh deno-project-starter_db_1:27017 && deno run --allow-net /home/deno/app/server.ts"

    db:
        image: mongo:4.1.8-xenial
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
        volumes:     
            - dbdata:/data/db
        networks:
            - app-network  
    
networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        